package com.spring.odi.framework.util;

public class CommonConstant {
    public static String REDIS_PLATEFORM_TEMPLATE_ID = "REDIS_PLATEFORM_TEMPLATE_ID_";

    public static String REDIS_PLATEFORM_TEMPLATE_CODE = "REDIS_PLATEFORM_TEMPLATE_CODE_";

    public static String REDIS_PLATEFORM_TABLE_CONDITION_LIST_TEMPLATEID = "REDIS_TABLE_CONDITION_LIST_TEMPLATEID_";

    public static String REDIS_PLATEFORM_TABLE_VIEW_LIST_TEMPLATEID = "REDIS_TABLE_VIEW_LIST_TEMPLATEID_";

    public static String REDIS_PLATEFORM_TABLE_OP_LIST_CONDITIONID = "REDIS_TABLE_OP_LIST_CONDITIONID_";

    public static String REDIS_PLATEFORM_TEMPLATE_SAVE_BEAN_ID = "REDIS_TEMPLATE_SAVE_BEAN_ID_";

    public static String REDIS_PLATEFORM_TEMPLATE_SAVE_ID = "REDIS_TEMPLATE_SAVE_ID_";

    public static String REDIS_PLATEFORM_TEMPLATE_KEY_TEMPLATESAVE_ID = "REDIS_TEMPLATE_KEY_TEMPLATESAVE_ID_";

    public static String REDIS_PLATEFORM_TEMPLATE_CONDITION_TEMPLATESAVE_ID = "REDIS_TEMPLATE_CONDITION_TEMPLATESAVE_ID_";

    public static String REDIS_PLATEFORM_TEMPLATE_CONDITION_DETAIL_TEMPLATESAVE_ID = "REDIS_TEMPLATE_CONDITION_DETAIL_TEMPLATESAVE_ID_";
}
